// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMt6tPl5R-pwPfcC9brLugXiVnyX0NDJo',
    appId: '1:789395642028:web:7951a71d3750457fb47109',
    messagingSenderId: '789395642028',
    projectId: 'user-validator-f7e8c',
    authDomain: 'user-validator-f7e8c.firebaseapp.com',
    storageBucket: 'user-validator-f7e8c.appspot.com',
    measurementId: 'G-KD8N9NSLBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf3IKJiSxkPAiFX7HfYh-TcdXDvJdl_b8',
    appId: '1:789395642028:android:39cce126ad6db2b7b47109',
    messagingSenderId: '789395642028',
    projectId: 'user-validator-f7e8c',
    storageBucket: 'user-validator-f7e8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_JYMznNKHxhVS2j2f6McLZd4SjRYh1RI',
    appId: '1:789395642028:ios:a22e6d6c4fd695cfb47109',
    messagingSenderId: '789395642028',
    projectId: 'user-validator-f7e8c',
    storageBucket: 'user-validator-f7e8c.appspot.com',
    iosBundleId: 'com.internshiptest.uservalidator.userValidator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_JYMznNKHxhVS2j2f6McLZd4SjRYh1RI',
    appId: '1:789395642028:ios:a22e6d6c4fd695cfb47109',
    messagingSenderId: '789395642028',
    projectId: 'user-validator-f7e8c',
    storageBucket: 'user-validator-f7e8c.appspot.com',
    iosBundleId: 'com.internshiptest.uservalidator.userValidator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMt6tPl5R-pwPfcC9brLugXiVnyX0NDJo',
    appId: '1:789395642028:web:739cf36a71d8f488b47109',
    messagingSenderId: '789395642028',
    projectId: 'user-validator-f7e8c',
    authDomain: 'user-validator-f7e8c.firebaseapp.com',
    storageBucket: 'user-validator-f7e8c.appspot.com',
    measurementId: 'G-KJJE8LHHLP',
  );

}